// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Maths = require("./Maths.bs.js");

console.log(Maths.square(2));

function example(param) {
  return Maths.sum(1, param);
}

function other(param) {
  return Maths.sum(4, param);
}

console.log(Maths.sum(1, 7));

console.log(Maths.sum(4, 4));

console.log(Maths.multiply(2, 3));

exports.example = example;
exports.other = other;
/*  Not a pure module */
