// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function square(x) {
  return Math.imul(x, x);
}

function sum(a, b) {
  return a + b | 0;
}

function multiply(a, b) {
  return Math.imul(a, b);
}

exports.square = square;
exports.sum = sum;
exports.multiply = multiply;
/* No side effect */
